### ISSUE TITLE
Unit support

### ISSUE THREAD

**Issue by parnoldx** [flaviut/qalculate-wasm#1]
Nice project. 
It seems that the unit support is not working right now.

**Comment by flaviut** [comment]
Yup! The unit data needs to be loaded from the filesystem, and the browser doesn't support accessing the filesystem.

I have some ideas on how to do fix that, but I'm holding off on implementing them until I hear back on https://github.com/Qalculate/libqalculate/issues/225. I'd like to be certain that I can get my changes applied upstream.
